# =============================================================================
# nylbot-merge - PR Merge Automation Action
# =============================================================================
# A composite action that provides automated PR merging via the `/nylbot merge`
# command in PR comments. This action encapsulates all the validation and
# merge logic previously in the reusable workflow.
#
# USAGE:
# This action is called from a workflow triggered by issue_comment events.
#
#   on:
#     issue_comment:
#       types: [created]
#
#   jobs:
#     nylbot-merge:
#       runs-on: ubuntu-latest
#       permissions:
#         contents: write
#         pull-requests: write
#         issues: write
#       steps:
#         - uses: tomody-dev/nylbot/merge@v1
#           with:
#             github-token: ${{ secrets.GITHUB_TOKEN }}
#
# LIMITATIONS:
# - Fork PRs are NOT supported (GITHUB_TOKEN has limited permissions)
# - Only organization owners, members, or collaborators with write access
#   can use the `/nylbot merge` command
#
# THIRD-PARTY LICENSES:
# - Twemoji graphics (https://github.com/twitter/twemoji) are used for emoji
#   display compatibility. Licensed under CC-BY 4.0.
# =============================================================================

name: 'nylbot-merge'
description: 'Automated PR merging with validation checks via /nylbot merge command'

inputs:
  github-token:
    description: 'GitHub token for API authentication'
    required: true
  release-branch-prefix:
    description: 'OPTIONAL: Prefix for release branches (e.g., "release/")'
    required: false
    default: 'release/'
  develop-branch:
    description: 'OPTIONAL: Name of the develop branch'
    required: false
    default: 'develop'
  sync-branch-prefix:
    description: 'OPTIONAL: Prefix for sync branches used in back-merges (e.g., "fix/sync/")'
    required: false
    default: 'fix/sync/'
  mergeable-retry-count:
    description: 'OPTIONAL: Number of retries for waiting on GitHub to calculate mergeable status (valid range: 1-20)'
    required: false
    default: '5'
  mergeable-retry-interval:
    description: 'OPTIONAL: Interval in seconds between retries (valid range: 1-60)'
    required: false
    default: '10'

outputs:
  result:
    description: 'Result of the merge operation (merged, skipped, failed, already_merged)'
  merge-method:
    description: 'Merge method used (squash or merge)'

runs:
  using: 'node24'
  main: '../dist/merge.js'
